### ISSUE TITLE
Suggestion: "see also" or similar

### ISSUE THREAD

**Issue by raymondben** [ropenscilabs/tl#5]
Worth considering "see also" type references in here? e.g. if I `tl::dr(base::grepl)` maybe it's because I don't know about `stringr::str_detect`? Or (more interesting to me) maybe I'm writing a package and want something that works like [insert favourite heavyweight-package function here] but which only uses base, in order to minimise my package dependencies.

Perhaps that could be a different function? (`tl::alt()`? `tl::aka()`?)

**Comment by goldingn** [comment]
Nice. Someone (Miles?) suggested adding links to other resources on the page, e.g. the helpfile, explainer blogs etc. A 'see also' section with those and related functions would be great. Perhaps at the bottom of the page, and preferably as minimal as possible.

Relatedly, code to help de-bloat dependencies like you suggest would be really handy. Maybe as an extension to the goodpractice package. Project for next year!
